# Versão da sintaxe do Docker Compose
version: '3.8'

# Definição dos serviços (contêineres)
services:
  # Nome do nosso serviço de banco de dados
  postgres-db:
    # Usa a imagem oficial do PostgreSQL, travada na versão 16 (evita quebras inesperadas)
    image: postgres:16
    # Nome do contêiner que será criado
    container_name: postgres-db
    # Reinicia o contêiner automaticamente em caso de falha
    restart: always
    # Mapeia a porta 5432 do contêiner para a porta 5432 da sua máquina
    ports:
      - "5432:5432"
    # Variáveis de ambiente para configurar o PostgreSQL
    environment:
      # CUIDADO: Estamos usando variáveis que virão de um arquivo .env para segurança
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Volume para persistir os dados do banco de dados
    volumes:
      # 'pgdata' é um "volume nomeado" gerenciado pelo Docker.
      # Se o contêiner for removido, os dados neste volume NÃO serão perdidos.
      - pgdata:/var/lib/postgresql/data

# Definição dos volumes nomeados
volumes:
  pgdata: